
- name: Reset
  ios_config:
    lines:
    - "default interface {{ interface_prefix }}/{{ portchannels.start  | int + (item | int) * 2 }}"
    - "default interface {{ interface_prefix }}/{{ portchannels.start | int + (item | int) * 2 + 1 }}"
  with_sequence: start=0 end="{{ ((1 + portchannels.end - portchannels.start)/2) | int }}"


- name: Setup variables
  ios_linkagg:
      group: "{{ item | int + 1 }}"
      mode: active
      members:
          - "{{ interface_prefix }}/{{ portchannels.start  | int + (item | int) * 2 }}"
          - "{{ interface_prefix }}/{{ portchannels.start | int + (item | int) * 2 + 1 }}"
  with_sequence: start=0 end="{{ ((1 + portchannels.end - portchannels.start)/2) | int }}"

- name: Setup Port Channels vlan
  ios_config:
    lines:
    - "switchport mode trunk"
    - "switchport trunk allowed vlan {{ vlans | difference(po_excluded_vlans) | join(',') }}"
    - spanning-tree guard loop
    parents:
        - "interface Port-Channel{{ item | int + 1 }}"
  with_sequence: start=0 end="{{ ((1 + portchannels.end - portchannels.start)/2) | int }}"
